### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Kattusshka/kinozal_0506#1]
1)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/121766321-9eb32300-cb59-11eb-9f26-8c78d61a7630.png)

2)
отступы 6 пробелов.
допускается 2 или 4, но для всего проекта, включая html css js
![image](https://user-images.githubusercontent.com/8464662/121766327-aa064e80-cb59-11eb-86d3-6d88810b7ade.png)

3)
чем обосновано использование пустых строк более 1 по коду?
![image](https://user-images.githubusercontent.com/8464662/121766345-c3a79600-cb59-11eb-875c-027539b9f0b6.png)

**Comment by Kattusshka** [comment]
Ошибку 1 и 3 исправила. По 2-й - как я могу добиться уменьшения отступов,
мне же для этого половину структуры убрать нужно? Не совсем понимаю(

сб, 12 июн. 2021 г. в 08:41, Andrey ***@***.***>:
